version: '3.7'

services:
  ui-builder:
    container_name: ui-builder
    build:
      context: .
      dockerfile: Dockerfile.ui-builder
    volumes:
      - ui-build:/project/bfx-report-ui/build

  linux-builder:
    container_name: linux-builder
    build:
      context: .
      dockerfile: Dockerfile.linux-builder
    environment:
      ELECTRON_CACHE: /root/.cache/electron
      ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
    volumes:
      - ui-build:/project/bfx-report-ui/build
      - ./dist:/project/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder
    depends_on:
      - ui-builder

  win-builder:
    container_name: win-builder
    build:
      context: .
      dockerfile: Dockerfile.win-builder
    environment:
      ELECTRON_CACHE: /root/.cache/electron
      ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
    volumes:
      - ui-build:/project/bfx-report-ui/build
      - ./dist:/project/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder
    depends_on:
      - ui-builder

  mac-builder:
    container_name: mac-builder
    build:
      context: .
      dockerfile: Dockerfile.mac-builder
    environment:
      ELECTRON_CACHE: /root/.cache/electron
      ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
    volumes:
      - ui-build:/project/bfx-report-ui/build
      - ./dist:/project/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder
    depends_on:
      - ui-builder

volumes:
  ui-build:
